### ISSUE TITLE
Extend List of GitHub Enterprise Users w/ Usage Stats

### ISSUE THREAD

**Issue by mopore** [PRODYNA/github-users#8]
Add the following values of the GitHub Enterprise user accounts
- Amount of commits
- Amount of PRs created
- Amount of issues created
- Amount of comments on issues

**Comment by dkrizic** [comment]
```
query {
  enterprise(slug:"prodyna") {
    slug
    name
    ownerInfo {
      samlIdentityProvider {
        externalIdentities(first:10) {
          pageInfo {
            hasNextPage
            startCursor
          }
          edges {
            node {
              user {
                login
                name
                organizations(first:99) {
                  nodes {
                    name
                  }
                }
                contributionsCollection {
                  contributionCalendar {
                    totalContributions
                  }
                }
              }
              samlIdentity {
                nameId
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by dkrizic** [comment]
First version only contains total Contributions, can be extended later.

**Comment by mopore** [comment]
I assume that total contributions not only includes commits.
Sounds good enough then.

**Comment by dkrizic** [comment]
Yes, but obviously not only limited to the current enterprise or organisation. The current result is visible here:

https://github.com/PRODYNA/github-housekeeping/wiki/Enterprise-users

But currently it definitely helps us to find users doing nothing in GitHub.
